[[redirects]]
from = "/resources/slide_ppi_edufest_2023"
to = "https://tumde-my.sharepoint.com/:b:/g/personal/yudhistira_arief_wibowo_tum_de/Ec-C1PmC4VhOqjQ0jBBu1ukBahmWxrgul1vLQMKjnbC3UA?e=fqP0yc"
status = 302
force = true
